// Code generated by https://github.com/j178/leetgo.

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
8
[4,1,8,4,5]
[5,6,1,8,4,5]
2
3
output:
Intersected at '8'

input:
2
[1,9,1,2,4]
[3,2,4]
3
1
output:
Intersected at '2'

input:
0
[2,6,4]
[1,5]
3
2
output:
No intersection
`

func Test_getIntersectionNode(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, getIntersectionNode, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
