// Code generated by https://github.com/j178/leetgo.

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
[1,2,2,1]
[2,2]
output:
[2]

input:
[4,9,5]
[9,4,9,8,4]
output:
[9,4]
`

func Test_intersection(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, intersection, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
