// Code generated by https://github.com/j178/leetgo.

package main

import (
	"testing"
)

var testcases = `
input:
["MyLinkedList","addAtHead","addAtTail","addAtIndex","get","deleteAtIndex","get"]
[[],[1],[3],[1,2],[1],[1],[1]]
output:
[null,null,null,null,2,null,3]
`

func Test_Constructor(t *testing.T) {
	m := Constructor()
	m.AddAtTail(2)
	m.AddAtTail(1)
	m.AddAtHead(0)
	m.AddAtIndex(3, 3)
	head := m.head
	for head != nil {
		println(head.val)
		head = head.next
	}
}
