// Code generated by https://github.com/j178/leetgo.

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
"abcdefg"
2
output:
"bacdfeg"

input:
"abcd"
2
output:
"bacd"
`

func Test_reverseStr(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, reverseStr, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
