// Code generated by https://github.com/j178/leetgo.

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
[1,2,3,4,5]
output:
[5,4,3,2,1]

input:
[1,2]
output:
[2,1]

input:
[]
output:
[]
`

func Test_reverseList(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, reverseList, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
