// Code generated by https://github.com/j178/leetgo.

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
"the sky is blue"
output:
"blue is sky the"

input:
"  hello world  "
output:
"world hello"

input:
"a good   example"
output:
"example good a"
`

func Test_reverseWords(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, reverseWords, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
