// Code generated by https://github.com/j178/leetgo.

package main

import (
	"testing"
)

var testcases = `
input:
[1,2,3,4]
output:
[2,1,4,3]

input:
[]
output:
[]

input:
[1]
output:
[1]
`

func Test_swapPairs(t *testing.T) {
	head := new(ListNode)
	head.Val = 1
	head.Next = new(ListNode)
	head.Next.Val = 2
	r := swapPairs(head)
	for r != nil {
		println(r.Val)
		r = r.Next
	}
}
