// Code generated by https://github.com/j178/leetgo.

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
[2,1,3]
1
output:
2
`

func Test_inorderSuccessor(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, inorderSuccessor, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
